### ISSUE TITLE
Installation on R 3.4.0

### ISSUE THREAD

**Issue by asmagen** [waldronlab/TCGAutils#11]
Hello,

The latest R version installed on my servers is R 3.4.0. I don't have control on updating it to 3.5.0 for now.

Is it possible to install this package on R 3.4.0 somehow?

Thanks,
Assaf

**Comment by LiNk-NY** [comment]
Hi Assaf, 

You can create a GitHub fork of `TCGAutils` and modify the `Depends:` field in the `DESCRIPTION`
file and install it via your GitHub fork. 

I can't guarantee that it will work for `R 3.4.0` since the package was developed with  `R 3.5.0`.

Note that installing `R 3.5.0` in your `$HOME` folder may also be an option.

Regards,
Marcel
