### ISSUE TITLE
UUIDtoBarcode not recognising file_id after R update

### ISSUE THREAD

**Issue by JuliaArizanova** [waldronlab/TCGAutils#31]
Hi, Thank you so much for this package!

I am trying to re-run a script I have used in the past, and getting an error when trying to convert file_ids using UUIDtoBarcode (although they are the exact same file_ids as previously).

`UUIDtoBarcode("691ec8c8-17b3-4c26-83f6-bd76817d9238", from_type = "file_id")`

`Error in UUIDtoBarcode("691ec8c8-17b3-4c26-83f6-bd76817d9238", from_type = "file_id") : 
  No barcodes found, only case and file UUIDs are supported.`

R version: 4.1.2 (2021-11-01)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Monterey 12.1

**Comment by LiNk-NY** [comment]
Hi Julia, @JuliaArizanova 
This is not an issue for TCGAutils. It may be that the file is removed from the GDC:
https://portal.gdc.cancer.gov/files/691ec8c8-17b3-4c26-83f6-bd76817d9238 
Please contact the GDC directly. 
Best,
Marcel

**Comment by shadihames** [comment]
I am running into the same issue. The problem is that I have files from the previous release. The version 32 release in March has overhauled a lot of files and so subsequently changed uuids. Is there any way that we can match the previous release uuid's to barcodes? This is an issue with GenomicDataCommons as well, and I'm not sure of any way to get around it for those of use who can't download all of the newly released data yet. 

Thanks.

**Comment by LiNk-NY** [comment]
Files in the previous release are no longer hosted in the GDC. 
You can try checking the maps here: https://github.com/NCI-GDC/gdc-docs/tree/develop/docs/Data/Release_Notes/GCv36_Manifests taken from https://docs.gdc.cancer.gov/Data/Release_Notes/Data_Release_Notes
or use `TCGAutils::UUIDhistory` to get the version history of a file. 

It's not really an issue with `GenomicDataCommons`, per se, but with the GDC versioned releases.
